---
- hosts: all
  become: yes
  tasks:
  - name: updating packages and install apache2
    apt:
      name: apache2
      update_cache: yes
      state: present
    notify:
    - restart apache2 service
    when: ansible_os_family == "Debian"
  - name: install apche2 in redhat
    yum:
      name: httpd
      state: present
    notify:
    - restart httpd service
    when: ansible_os_family == "RedHat"  
  - name: Install php packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php 
      - libapache2-mod-php
      - php-mcrypt
      - php-mysql
    notify:
    - restart apache2 service
    when: ansible_os_family == "Debian"
  - name: Install php and restart httpd
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - php-mysql  
    notify:
    - restart httpd service
    when: ansible_os_family == "RedHat"
  handlers:
  - name: restart apache2 service
    service:
      name: apache2
      enabled: yes
      state: restarted
    when: ansible_os_family == "Debian"
  - name: restart httpd service
    service:
      name: httpd
      enabled: yes
      state: restarted
    when: ansible_os_family == "RedHat"           