---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: Installing apache2
    yum:
      name: httpd
      state: present
    notify:
    - restart httpd
    when: ansible_os_family == "RedHat"
  - name: Install php
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - php-mysql
    notify:
    - restart httpd
  when: ansible_os_family == "RedHat"
  handlers:
  - name: restart httpd
    service:
      name: httpd
      enabled: yes
      state: restarted
    when: ansible_os_family == "RedHat"